In [17]:
import numpy as np
my_list = [1,2,3]
print(my_list)
print(np.array(my_list))

[1, 2, 3]
[1 2 3]


ARRAY

In [18]:
my__matrix = [[1,2,3],[4,5,6],[5,6,7]]
print(my__matrix)
np.array(my__matrix)
print(np.array(my__matrix))

[[1, 2, 3], [4, 5, 6], [5, 6, 7]]
[[1 2 3]
 [4 5 6]
 [5 6 7]]


ARANGE

In [19]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


(start,end,step)

In [20]:
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


first 50 odd numbers

In [21]:
print(np.arange(1,102,2))

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101]


zeros and one

In [22]:
print(np.zeros(3))
print(np.zeros((6,9)))
print(np.ones(4))
print(np.ones((4,5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


linspace

In [23]:
print(np.linspace(0,10,3))
print(np.linspace(0,10,50))
print(np.linspace(0,100,25))

[ 0.  5. 10.]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]


eye

In [24]:
print(np.eye(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


random

In [25]:
print(np.random.rand(2))
print(np.random.rand(5))
print(np.random.rand(9,6))

[0.90922463 0.43901504]
[0.44148802 0.46525688 0.18468315 0.74425024 0.9308625 ]
[[0.12999593 0.41132961 0.36028532 0.7885613  0.44762438 0.40216465]
 [0.90594664 0.2368533  0.42927738 0.9994347  0.14659984 0.38397131]
 [0.43534315 0.52146139 0.65830535 0.37156929 0.52797433 0.96010138]
 [0.46794013 0.56505096 0.54810054 0.29003059 0.94276006 0.87559655]
 [0.48736105 0.8409904  0.99562647 0.47790135 0.77028915 0.46395482]
 [0.51896801 0.93463554 0.70097116 0.74870075 0.51983957 0.60936581]
 [0.07389443 0.18051342 0.4965113  0.80874453 0.90419754 0.37497757]
 [0.93239258 0.48878147 0.09729919 0.38009376 0.36169189 0.63469326]
 [0.25319361 0.61060646 0.49628498 0.73299172 0.48675434 0.37818619]]


randn

In [26]:
print(np.random.randn(2))
print(np.random.randn(5,5))

[-1.01228461  0.64969455]
[[ 0.17212355 -0.59762299 -1.25115336  0.93483688  1.0638393 ]
 [-0.30366512 -1.36637744  1.1804364   2.02003312  0.19832396]
 [ 0.33761919  0.65720581  0.79041228 -1.11518609  0.73985535]
 [ 0.59656593 -0.14607834  1.32766079  0.72661037  2.05150764]
 [ 0.11379605  0.66864318  1.07648224 -0.51391843  1.14056284]]


randint

In [27]:
print(np.random.randint(1,100))
print(np.random.randint(1,100,10))

67
[44 15 32 53  9 19 64  7 35 55]


array attributes and methods

In [28]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[30 24 14 20  1 22 15 13 44  3]


reshape

In [29]:
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


max min argmax argmin

In [30]:
print(ranarr)
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())
print(ranarr.argmin())

[30 24 14 20  1 22 15 13 44  3]
44
8
1
4


shape

In [31]:
print(arr.shape)
print(arr.reshape(1,25))
print(arr.reshape(1,25).shape)
print(arr.reshape(25,1))
print(arr.reshape(25,1).shape)

(25,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
(1, 25)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
(25, 1)


dtype data type

In [32]:
print(arr.dtype)

int32
